# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
  

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'


    - name: Build with Maven
      run: mvn clean install

# what else want to do on occuring of events
# login to docker hub
# create docker image
# push to docker hub
    - name: build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v5
    - name: Build & push Docker image
      with:
              image: shivam9984/springboot-ci-cd
              tags: v1, latest
              registry: registry-url.io
              dockerfile: Dockerfile.ci
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

