# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
  

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
              image: shivam9984/springboot-ci-cd
              tags: v1, latest
              registry: docker.io
              dockerfile: Dockerfile
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

