# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
  

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:


# what else want to do on occuring of events
# login to docker hub
# create docker image
# push to docker hub
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: shivam9984/springboot-ci-cd:latest
